name: YourOwnVariables
main: varplugin.Main
version: 3.0
author: Haizenfell
api-version: 1.13
depend: [PlaceholderAPI]
commands:
  yov:
    description: Variable Management
    usage: /<command> <export|set|add|delete|check> <variable> [value] [player] [-s]
    aliases: [var]
